import { z } from "zod";
import {
  defineTool, durationMs, fieldNames, headerNames, httpMethods, list, noConfig, origins, positiveCount, route, routeFilter, routes,
} from "./common";

const DEFAULT_METHODS = ["GET", "HEAD", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"];

export const anomalyTools = {
  business_logic_tampering: defineTool({
    id: "business_logic_tampering",
    displayName: "Business logic tampering",
    category: "anomaly",
    contextType: "full",
    description: "Rejects negative quantities, prices and out-of-range discounts; flags totals below their line items.",
    config: z.strictObject({
      quantityFields: fieldNames().default(["quantity", "qty", "count", "units", "amountofitems"]),
      priceFields: fieldNames().default(["price", "unitprice", "amount", "cost", "subtotal", "fee"]),
      totalFields: fieldNames().default(["total", "totalprice", "totalamount", "grandtotal", "ordertotal"]),
      percentFields: fieldNames().default(["discount", "discountpercent", "percentoff", "rebate"]),
      maxQuantity: positiveCount(1_000_000_000).default(10_000),
      totalTolerance: z.number().finite().min(0).max(1_000_000).default(0.01).describe("Rounding allowed between a total and its line items, in currency units."),
    }),
  }),
  content_type_mismatch: defineTool({
    id: "content_type_mismatch",
    displayName: "Content-Type mismatch",
    category: "anomaly",
    contextType: "full",
    description: "Flags bodies whose content does not match the declared Content-Type, or that have none.",
    config: noConfig(),
  }),
  double_encoding: defineTool({
    id: "double_encoding",
    displayName: "Double encoding",
    category: "anomaly",
    contextType: "field",
    description: "Flags values that reveal filtered characters only after more than one round of percent-decoding.",
    config: noConfig(),
  }),
  duplicate_request: defineTool({
    id: "duplicate_request",
    displayName: "Duplicate request",
    category: "anomaly",
    contextType: "full",
    description: "Flags the same request (by hash) sent again to the same endpoint within a window.",
    config: z.strictObject({
      windowMs: durationMs().default(10_000),
    }),
  }),
  encoded_payload: defineTool({
    id: "encoded_payload",
    displayName: "Encoded payload",
    category: "anomaly",
    contextType: "field",
    description: "Decodes base64, hex and percent-encoded blobs and re-scans them with the injection detectors.",
    config: noConfig(),
  }),
  entropy_analysis: defineTool({
    id: "entropy_analysis",
    displayName: "Entropy analysis",
    category: "anomaly",
    contextType: "field",
    description: "Flags long values that look random (encrypted or encoded payloads) in fields meant for human text.",
    config: z.strictObject({
      minLength: positiveCount(8192).default(32).describe("Shorter words can't carry a meaningful entropy estimate."),
      thresholds: z.strictObject({
        hex: z.number().min(0).max(8).default(3.7),
        base64: z.number().min(0).max(8).default(5.0),
        mixed: z.number().min(0).max(8).default(5.2),
      }).prefault({}).describe("Bits per character above which a value looks random, per character set."),
      randomFields: fieldNames().default([
        "password", "passwd", "token", "accesstoken", "refreshtoken", "idtoken", "csrf", "csrftoken", "xsrftoken", "nonce",
        "state", "code", "codeverifier", "codechallenge", "signature", "sig", "hash", "apikey", "secret", "clientsecret",
        "sessionid", "captcha", "recaptcharesponse", "gcaptcharesponse", "hcaptcharesponse", "otp",
      ]).describe("Fields that are random by design (tokens, nonces, passwords)."),
    }),
  }),
  honeypot_endpoint: defineTool({
    id: "honeypot_endpoint",
    displayName: "Honeypot endpoint",
    category: "anomaly",
    contextType: "full",
    description: "Rejects any request to a decoy route no legitimate client calls.",
    config: z.strictObject({
      routes: routeFilter().describe("Decoy routes. Omitted, every endpoint the step is attached to is a decoy."),
    }),
  }),
  honeypot_field: defineTool({
    id: "honeypot_field",
    displayName: "Honeypot field",
    category: "anomaly",
    contextType: "full",
    description: "Rejects requests that fill in hidden form inputs a person never sees.",
    config: z.strictObject({
      fields: fieldNames().min(1),
    }),
  }),
  mass_assignment: defineTool({
    id: "mass_assignment",
    displayName: "Mass assignment",
    category: "anomaly",
    contextType: "full",
    description: "Flags state-changing requests that set privileged properties (role, balance, owner) on a record.",
    config: z.strictObject({
      privilegedFields: fieldNames().default([
        "role", "roles", "isadmin", "admin", "issuperuser", "superuser", "isstaff", "staff", "permissions", "privileges",
        "scopes", "groups", "accesslevel", "usertype", "accounttype", "verified", "isverified", "emailverified",
        "phoneverified", "approved", "isapproved", "balance", "credit", "credits", "walletbalance", "ownerid", "owner",
        "tenantid", "organizationid", "orgid", "createdby", "plan", "subscriptiontier", "ispremium", "isbanned", "locked",
        "passwordhash", "apikey", "mfaenabled", "twofactorenabled",
      ]),
    }),
  }),
  method_anomaly: defineTool({
    id: "method_anomaly",
    displayName: "HTTP method anomaly",
    category: "anomaly",
    contextType: "full",
    description: "Rejects debugging and unknown HTTP methods, and methods a route does not accept.",
    config: z.strictObject({
      defaultMethods: httpMethods().default(DEFAULT_METHODS).describe("Methods accepted on routes without their own entry."),
      routes: list(z.strictObject({ route: route(), methods: httpMethods() }), 500).default([]).describe("Per-route methods; the most specific matching route wins."),
    }),
  }),
  method_override: defineTool({
    id: "method_override",
    displayName: "HTTP method override",
    category: "anomaly",
    contextType: "full",
    description: "Rejects method overrides to dangerous or state-changing methods; flags any other override.",
    config: noConfig(),
  }),
  overlong_utf8: defineTool({
    id: "overlong_utf8",
    displayName: "Overlong UTF-8",
    category: "anomaly",
    contextType: "field",
    description: "Rejects escaped overlong UTF-8 and encoded surrogates; flags other invalid escaped UTF-8.",
    config: noConfig(),
  }),
  private_ip: defineTool({
    id: "private_ip",
    displayName: "Private IP",
    category: "anomaly",
    contextType: "full",
    description: "Flags clients connecting from private, loopback, link-local or other reserved addresses.",
    config: noConfig(),
  }),
  profanity_filter: defineTool({
    id: "profanity_filter",
    displayName: "Profanity filter",
    category: "anomaly",
    contextType: "field",
    description: "Rejects text containing listed terms, including leetspeak, masked, spaced and stretched spellings.",
    config: z.strictObject({
      terms: list(z.string().regex(/^[a-z]{2,40}$/, "lowercase letters only"), 5000).min(1).default([
        "fuck", "motherfucker", "shit", "bullshit", "horseshit", "shithead", "dipshit", "bitch", "bastard",
        "asshole", "arsehole", "dumbass", "jackass", "dickhead", "cunt", "piss", "wanker", "twat",
        "douchebag", "bollocks",
      ]).describe("Lowercase terms; common endings (s, ed, ing, ...) are matched automatically."),
      maxWords: positiveCount(100_000).default(5000).describe("Words scanned per value."),
    }),
  }),
  referer_anomaly: defineTool({
    id: "referer_anomaly",
    displayName: "Referer anomaly",
    category: "anomaly",
    contextType: "full",
    description: "Flags requests to same-site routes that arrive without, or with a foreign, Origin or Referer.",
    config: z.strictObject({
      allowedOrigins: origins().min(1).describe("Origins of the application's own pages."),
      routes: routeFilter().describe("Routes only the application's own pages call. Omitted, every endpoint the step is attached to."),
    }),
  }),
  sequence_analysis: defineTool({
    id: "sequence_analysis",
    displayName: "Sequence analysis",
    category: "anomaly",
    contextType: "full",
    description: "Flags clients that scan many endpoints or walk sequential ids within a window.",
    config: z.strictObject({
      windowMs: durationMs().default(60_000),
      maxDistinctEndpoints: positiveCount(10_000).default(15).describe("More distinct endpoints than this from one client in the window is a scan."),
      minSequence: positiveCount(1000).default(5).describe("This many consecutive integer values on one endpoint is enumeration."),
    }),
  }),
  timestamp_replay: defineTool({
    id: "timestamp_replay",
    displayName: "Timestamp replay",
    category: "anomaly",
    contextType: "full",
    description: "Rejects signed requests with a stale, future or missing timestamp, or a reused nonce or signature.",
    config: z.strictObject({
      maxAgeMs: durationMs().default(300_000).describe("Signed requests older, or further in the future, than this are rejected."),
      signedRoutes: routes().default([]).describe("Routes whose requests must be signed; elsewhere only requests carrying a signature header are checked."),
      signatureHeaders: headerNames().min(1).default(["x-signature", "x-hub-signature-256", "x-request-signature", "stripe-signature", "x-webhook-signature"]),
      timestampHeaders: headerNames().default(["x-timestamp", "x-request-timestamp", "x-signature-timestamp"]),
      nonceHeaders: headerNames().default(["x-nonce", "x-request-nonce"]),
    }),
  }),
  timing_anomaly: defineTool({
    id: "timing_anomaly",
    displayName: "Timing anomaly",
    category: "anomaly",
    contextType: "full",
    description: "Flags forms submitted faster than a person can fill them, and bursts of state-changing requests.",
    config: z.strictObject({
      formRoutes: routeFilter().describe("Forms carrying a render time. Omitted, every endpoint the step is attached to."),
      renderTimeFields: fieldNames().default(["formrenderedat", "formts", "renderedat", "formstartedat"]).describe("Hidden field the form page fills with its render time (ms or s since epoch)."),
      minFillMs: durationMs().default(1500),
      maxClockSkewMs: durationMs().default(5000),
      minActionIntervalMs: durationMs().default(250).describe("`fastActionsInARow` state-changing requests each less than this apart are a burst."),
      fastActionsInARow: positiveCount(1000).min(2).default(5),
    }),
  }),
  unicode_normalization: defineTool({
    id: "unicode_normalization",
    displayName: "Unicode normalization",
    category: "anomaly",
    contextType: "field",
    description: "Flags text that turns into syntax or attack keywords under NFKC, and words mixing look-alike scripts.",
    config: noConfig(),
  }),
} as const;
