import { z } from "zod";
import { bytes, defineTool, durationMs, escalation, fieldNames, list, positiveCount, route, routeFilter } from "./common";

const MIB = 1_048_576;

export const resourceTools = {
  archive_expansion_ratio: defineTool({
    id: "archive_expansion_ratio",
    displayName: "Archive expansion ratio",
    category: "resource",
    contextType: "file",
    description: "Rejects archive uploads that expand too much (zip bombs), too far in total, or hold too many entries.",
    config: z.strictObject({
      maxRatio: positiveCount(1_000_000).default(100).describe("Uncompressed bytes per compressed byte."),
      minBytesForRatio: bytes().default(MIB).describe("Below this uncompressed size the ratio is ignored: tiny archives compress \"badly\" harmlessly."),
      maxUncompressedBytes: bytes(1_099_511_627_776).default(1_073_741_824).describe("Absolute cap regardless of ratio."),
      maxEntries: positiveCount(10_000_000).default(10_000),
    }),
  }),
  array_length: defineTool({
    id: "array_length",
    displayName: "Array length",
    category: "resource",
    contextType: "full",
    description: "Rejects bodies with an oversized array or too many array elements in total.",
    config: z.strictObject({
      maxArrayLength: positiveCount(10_000_000).default(1000),
      maxTotalElements: positiveCount(10_000_000).default(10_000),
    }),
  }),
  compressed_body_ratio: defineTool({
    id: "compressed_body_ratio",
    displayName: "Compressed body ratio",
    category: "resource",
    contextType: "full",
    description: "Rejects compressed request bodies that decompress too far (gzip bombs), stacked or unknown encodings.",
    config: z.strictObject({
      maxRatio: positiveCount(1_000_000).default(100),
      minBytesForRatio: bytes().default(MIB).describe("Small bodies compress \"too well\" harmlessly."),
      maxDecompressedBytes: bytes().default(10 * MIB),
      maxEncodings: positiveCount(10).default(2).describe("\"gzip, gzip, gzip, br\" stacks bombs inside bombs."),
    }),
  }),
  concurrent_connections: defineTool({
    id: "concurrent_connections",
    displayName: "Concurrent connections",
    category: "resource",
    contextType: "full",
    description: "Rejects clients with too many requests in flight at once.",
    config: z.strictObject({
      maxInFlight: positiveCount(100_000).default(20),
      assumedLatencyMs: durationMs(600_000).default(1000).describe("Tools only see a request start, so a request is assumed to be in flight this long."),
    }),
  }),
  cookie_size: defineTool({
    id: "cookie_size",
    displayName: "Cookie count and size",
    category: "resource",
    contextType: "full",
    description: "Rejects more cookies, larger cookies or larger Cookie headers than browsers send.",
    config: z.strictObject({
      maxCookies: positiveCount(10_000).default(50).describe("RFC 6265 asks browsers to support at least 50 cookies of 4096 bytes per domain."),
      maxCookieBytes: positiveCount(MIB).default(4096),
      maxTotalBytes: positiveCount(MIB).default(8192),
    }),
  }),
  endpoint_quota: defineTool({
    id: "endpoint_quota",
    displayName: "Endpoint cost quota",
    category: "resource",
    contextType: "full",
    description: "Rejects clients that spend more than their cost budget on expensive routes within a window.",
    config: z.strictObject({
      costs: list(z.strictObject({ route: route(), cost: positiveCount(1_000_000) }), 500).min(1).describe("Relative cost of a request per route; the most specific route wins and unlisted routes are free."),
      costPerWindow: positiveCount(1_000_000_000).default(200),
      windowMs: durationMs().default(60_000),
    }),
  }),
  expensive_query: defineTool({
    id: "expensive_query",
    displayName: "Expensive query",
    category: "resource",
    contextType: "full",
    description: "Rejects wildcard-only searches; flags leading or repeated wildcards and sorts without a limit.",
    config: z.strictObject({
      searchFields: fieldNames().default(["q", "query", "search", "term", "keyword", "keywords", "filter", "name", "title", "text"]),
      sortFields: fieldNames().default(["sort", "sortby", "orderby", "order"]),
      limitFields: fieldNames().default(["limit", "pagesize", "perpage", "size", "take", "first", "top"]),
      minSearchLength: positiveCount(100).default(2).describe("Wildcard searches need at least this many real characters."),
    }),
  }),
  file_size: defineTool({
    id: "file_size",
    displayName: "File size",
    category: "resource",
    contextType: "file",
    description: "Rejects uploaded files larger than a limit.",
    config: z.strictObject({
      maxBytes: bytes().default(5 * MIB),
    }),
  }),
  graphql_complexity: defineTool({
    id: "graphql_complexity",
    displayName: "GraphQL complexity",
    category: "resource",
    contextType: "full",
    description: "Rejects GraphQL requests that are too deep, costly, wide, long or batched.",
    config: z.strictObject({
      maxDepth: positiveCount(1000).default(10),
      maxCost: positiveCount(100_000_000).default(1000).describe("Fields weighted by the page sizes of their ancestors."),
      maxAliases: positiveCount(100_000).default(30),
      maxFields: positiveCount(100_000).default(500),
      maxBatch: positiveCount(1000).default(5).describe("Operations in one HTTP request (array body)."),
      maxQueryBytes: positiveCount(10 * MIB).default(20_000),
    }),
  }),
  graphql_introspection: defineTool({
    id: "graphql_introspection",
    displayName: "GraphQL introspection",
    category: "resource",
    contextType: "full",
    description: "Rejects GraphQL introspection (__schema, __type) where it is not allowed.",
    config: z.strictObject({
      allowIntrospection: z.boolean().default(false).describe("Allow introspection, e.g. on a development deployment."),
    }),
  }),
  header_count: defineTool({
    id: "header_count",
    displayName: "Header count and size",
    category: "resource",
    contextType: "full",
    description: "Rejects requests with too many headers, too many header bytes, or one oversized header.",
    config: z.strictObject({
      maxHeaders: positiveCount(10_000).default(100),
      maxTotalBytes: positiveCount(10 * MIB).default(16_384),
      maxHeaderBytes: positiveCount(10 * MIB).default(8192),
    }),
  }),
  image_dimensions: defineTool({
    id: "image_dimensions",
    displayName: "Image dimensions",
    category: "resource",
    contextType: "file",
    description: "Rejects uploaded images too large to decode safely, and pixel floods (huge, nearly empty images).",
    config: z.strictObject({
      maxSide: positiveCount(1_000_000).default(16_384),
      maxPixels: positiveCount(10_000_000_000).default(50_000_000).describe("About 200 MB of RGBA once decoded."),
      maxPixelsPerByte: positiveCount(1_000_000).default(2000).describe("Real photos compress far less than this; pixel floods are mostly empty."),
    }),
  }),
  json_depth: defineTool({
    id: "json_depth",
    displayName: "JSON nesting depth",
    category: "resource",
    contextType: "full",
    description: "Rejects JSON bodies nested deeper than a limit.",
    config: z.strictObject({
      maxDepth: positiveCount(1000).default(20),
    }),
  }),
  multipart_part_count: defineTool({
    id: "multipart_part_count",
    displayName: "Multipart part count",
    category: "resource",
    contextType: "full",
    description: "Rejects multipart bodies with too many parts or files, or a missing, invalid or duplicated boundary.",
    config: z.strictObject({
      maxParts: positiveCount(100_000).default(100),
      maxFiles: positiveCount(10_000).default(20),
      maxBoundaryLength: positiveCount(70).default(70).describe("RFC 2046 allows 70."),
    }),
  }),
  object_key_count: defineTool({
    id: "object_key_count",
    displayName: "Object key count",
    category: "resource",
    contextType: "full",
    description: "Rejects bodies with too many keys in one object or in total (hash-table pressure).",
    config: z.strictObject({
      maxKeysPerObject: positiveCount(1_000_000).default(200),
      maxTotalKeys: positiveCount(10_000_000).default(5000),
    }),
  }),
  pagination_abuse: defineTool({
    id: "pagination_abuse",
    displayName: "Pagination abuse",
    category: "resource",
    contextType: "full",
    description: "Rejects page sizes, offsets and page numbers beyond limits, and non-plain values that dodge them.",
    config: z.strictObject({
      maxPageSize: positiveCount(1_000_000).default(100),
      maxOffset: positiveCount(1_000_000_000).default(10_000).describe("Deep OFFSET scans every skipped row."),
      maxPage: positiveCount(1_000_000_000).default(1000),
      pageSizeFields: fieldNames().default(["limit", "pagesize", "perpage", "size", "take", "first", "last", "count", "maxresults", "top", "rows", "pagelimit"]),
      offsetFields: fieldNames().default(["offset", "skip", "start", "from"]),
      pageFields: fieldNames().default(["page", "pagenumber", "pageindex", "p"]),
    }),
  }),
  query_param_count: defineTool({
    id: "query_param_count",
    displayName: "Query and form parameter count",
    category: "resource",
    contextType: "full",
    description: "Rejects requests with too many query or form parameters.",
    config: z.strictObject({
      maxQueryParams: positiveCount(100_000).default(100),
      maxFormParams: positiveCount(100_000).default(500),
    }),
  }),
  range_header_abuse: defineTool({
    id: "range_header_abuse",
    displayName: "Range header abuse",
    category: "resource",
    contextType: "full",
    description: "Rejects Range headers with too many or overlapping ranges; flags malformed ones.",
    config: z.strictObject({
      maxRanges: positiveCount(1000).default(10),
      maxHeaderLength: positiveCount(65_536).default(1024),
    }),
  }),
  rate_limit: defineTool({
    id: "rate_limit",
    displayName: "Rate limit",
    category: "resource",
    contextType: "full",
    description: "Rejects more requests per client and endpoint than allowed in a sliding window.",
    config: z.strictObject({
      limit: positiveCount(1_000_000).default(100).describe("Requests allowed per window."),
      windowMs: durationMs().default(60_000),
    }),
  }),
  request_size: defineTool({
    id: "request_size",
    displayName: "Request size",
    category: "resource",
    contextType: "full",
    description: "Rejects requests whose query, headers, body and files exceed a size limit.",
    config: z.strictObject({
      maxBytes: bytes().default(MIB),
    }),
  }),
  scraping_pattern: defineTool({
    id: "scraping_pattern",
    displayName: "Scraping pattern",
    category: "resource",
    contextType: "full",
    description: "Flags clients covering much of a catalog or walking its pages in order.",
    config: z.strictObject({
      routes: routeFilter().describe("Catalog routes. Omitted, every endpoint the step is attached to."),
      windowMs: durationMs().default(600_000),
      maxDistinctResources: positiveCount(1_000_000).default(150).describe("Product or listing pages a person won't open in one window."),
      minSequentialPages: positiveCount(100_000).default(20).describe("page=1,2,3,... walked in order."),
    }),
  }),
  slow_request: defineTool({
    id: "slow_request",
    displayName: "Slow request",
    category: "resource",
    contextType: "full",
    description: "Rejects requests whose headers or body arrive too slowly (slowloris, slow POST).",
    config: z.strictObject({
      maxHeadersMs: durationMs(600_000).default(10_000),
      maxBodyMs: durationMs(3_600_000).default(30_000),
      minBodyBytesPerSecond: positiveCount(100_000_000).default(500),
      minBodyMsForRate: durationMs(600_000).default(5000).describe("Shorter bodies have too little data for a meaningful rate."),
    }),
  }),
  sms_email_pumping: defineTool({
    id: "sms_email_pumping",
    displayName: "SMS / email pumping",
    category: "resource",
    contextType: "full",
    description: "Rejects clients sending codes to many destinations or flooding one; flags tenant-wide bursts and high-cost prefixes.",
    config: z.strictObject({
      routes: routeFilter().describe("Routes that send an SMS or email. Omitted, every endpoint the step is attached to."),
      windowMs: durationMs().default(600_000),
      clientDestinations: escalation({ suspicious: 5, block: 20 }, 100_000).describe("Distinct destinations one client sends to in the window."),
      tenantSuspiciousDestinations: positiveCount(10_000_000).default(500).describe("Distinct destinations all clients together send to: a distributed pumping campaign."),
      destinationMaxSends: positiveCount(100_000).default(5).describe("Messages one destination receives: one number or address bombed with codes."),
      highRiskPrefixes: list(z.string().regex(/^\+\d{1,6}$/, "+ and digits"), 1000).default([
        "+881", "+882", "+883", "+979", "+870", "+247", "+290", "+675", "+677", "+678", "+252", "+239",
      ]).describe("International prefixes with high termination fees, the ones toll-fraud rings own numbers in."),
      destinationFields: fieldNames().min(1).default(["phone", "phonenumber", "msisdn", "mobile", "to", "recipient", "email", "emailaddress", "destination"]),
    }),
  }),
  websocket_abuse: defineTool({
    id: "websocket_abuse",
    displayName: "WebSocket abuse",
    category: "resource",
    contextType: "full",
    description: "Rejects oversized or heavily fragmented WebSocket messages and message floods per connection.",
    config: z.strictObject({
      maxMessageBytes: positiveCount(100 * MIB).default(65_536),
      maxFramesPerMessage: positiveCount(1_000_000).default(100).describe("Heavy fragmentation is a parser DoS."),
      maxMessagesPerSecond: positiveCount(1_000_000).default(50),
      maxMessagesPerMinute: positiveCount(10_000_000).default(1000),
    }),
  }),
  xml_bomb: defineTool({
    id: "xml_bomb",
    displayName: "XML bomb",
    category: "resource",
    contextType: "full",
    description: "Rejects XML with recursive, deeply nested or hugely expanding internal entities (billion laughs).",
    config: z.strictObject({
      maxEntities: positiveCount(100_000).default(20),
      maxExpandedBytes: positiveCount(1_073_741_824).default(MIB).describe("What the entities would expand to, estimated without expanding them."),
      maxNesting: positiveCount(100).default(3),
    }),
  }),
} as const;
